### ISSUE TITLE
The use of target domain labels which are used to generate proposals to train adapter in the d_adapt

### ISSUE THREAD

**Issue by Shuntw6096** [thuml/Transfer-Learning-Library#130]
Hi, @JunguangJiang, thanks for sharing the code.
I have read the paper [Decoupled Adaptation for Cross-Domain Object Detection](https://arxiv.org/abs/2110.02578), but I found that how to generate proposals to train adapter is not metioned in the paper, and the target domain labels are used to re-assign the class during the process of generating target domain proposals in the implementation, but target domain labels can not be accessed in unsupervised domain adaptation. Is there a problem with this part?

https://github.com/thuml/Transfer-Learning-Library/blob/f1b24468404b1e64ff582d58ede6def1fc3056d5/examples/domain_adaptation/object_detection/d_adapt/d_adapt.py#L133

https://github.com/thuml/Transfer-Learning-Library/blob/f1b24468404b1e64ff582d58ede6def1fc3056d5/examples/domain_adaptation/object_detection/d_adapt/d_adapt.py#L46

https://github.com/thuml/Transfer-Learning-Library/blob/f1b24468404b1e64ff582d58ede6def1fc3056d5/tllib/alignment/d_adapt/proposal.py#L132-L136

Thanks

**Comment by JunguangJiang** [comment]
Thank you for your interest in our paper and your careful reading of the code.

There is no problem with it since we avoid using target domain labels during the training of the adaptor.
For instance, the target domain labels are not used in function `prepare_training_data` or `fit` (see [category_adaptation.py](https://github.com/thuml/Transfer-Learning-Library/blob/f1b24468404b1e64ff582d58ede6def1fc3056d5/examples/domain_adaptation/object_detection/d_adapt/category_adaptation.py)).

We record the target domain labels to make it easier to evaluate and report the adaptation performance of each adaptor.
If you don't have target domain labels in your dataset, you can just avoid calling function `validate` during the training of adaptors.

**Comment by Shuntw6096** [comment]
Thank for your reply, I have checked again, target domain labels only used in `validate`.
And I have tried `ResNet50` instaed of `ResNet101` for faster rcnn on cityscapes -> foggy cityscapes, adapter's backbone is `ResNet101`.

Here is detector's performance on target domain, result is similar to `ResNet101`.
| Setting | Backbone | person | rider | car | truck | bus | train | motorcycle | bicycle | mAP |
|:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|
| source only | resnet50 | 38.27 | 45.33 | 42.39 | 21.88 | 30.77 | 9.09 | 27.24 | 38.13 | 31.64 |
| phase 1 | resnet50   | 43.2 | 52.59 | 52.61 | 30.69| 35.13 | 22.67| 34.1| 45.75| 39.59 |
| phase 2 | resnet50   | 43.81| 54.38 | 54.16 | 32.89 | 39.02 | 31.39 | 35.53| 46.16| 42.17|

Thanks
