### ISSUE TITLE
about the generated image problem

### ISSUE THREAD

**Issue by KOOKOKOK** [thuml/Transfer-Learning-Library#217]
Hi,when i run examples/domain_adaptation/semantic_segmentationcycada.py,
![00448](https://github.com/thuml/Transfer-Learning-Library/assets/50746384/b8e2b5ac-6426-4541-87f0-de01fac6bc86)

threre is the phantom on the top of some genareted images.how can i eliminate them?

**Comment by thucbx99** [comment]
This is because the generator of CycleGAN fails to capture the complex scene in the picture. We also find this issue when performing translation on other datasets. So the problem is basically, how to train the generator (with limited amount of data & relative small generator). Maybe tuning some of hyper-parameters can be better. But I think this is an open problem for GAN now.

**Comment by KOOKOKOK** [comment]
thanks for your answer,i will try to improving💕
