### ISSUE TITLE
Could you give the detailed environment Requirement ?

### ISSUE THREAD

**Issue by zhguo9** [thuml/Transfer-Learning-Library#260]
Thank you for all the work you have done !!

however, there are several environment problems about numpy, torchvision and so on. So i'm asking for the probability of listing the environment.
for example , versions of python, numpy and so on . 
or just give the total environment for the TLL lib.

Thanks again!

following is some errors due to the environment problems.
![image](https://github.com/thuml/Transfer-Learning-Library/assets/126133450/bbea09dd-37d0-4be2-95fe-8cbf814883f8)
![image](https://github.com/thuml/Transfer-Learning-Library/assets/126133450/0175dcef-e0bd-4526-a2c5-f1fa2e2a3782)

**Comment by thucbx99** [comment]
We're sorry that the versions of torch and torchvision used in TLlib are somewhat out of date. At present, the issues that have received a lot of feedback are mainly related to torchvision and numpy. The version of torchvision can be referenced in each task (an example https://github.com/thuml/Transfer-Learning-Library/tree/master/examples/domain_adaptation/image_classification). For numpy, you can consider manually lowering the version, or modifying it according to the error report, mainly the type, etc. (for example, np.int should be modified to np.int32).

**Comment by Ambuj-Choudha** [comment]
I was able to setup the library properly currently, I am using the NVIDIA A100-PCIE-40GB GPU for my work. I have set it up with CUDA 12. If your GPU doesn't support this consider downgrading the torch version whch is compatible.


## Installation Steps and common issues with TL lib (in the virtual env)
1. Downgrade pip to version==22.0.2 (reference: https://github.com/pypa/pip/issues/12330)

2. run python Setup.py (from the repo directory)

3. Downgrade torch (pip install torch==2.2.1 torchvision==0.17.1 torchaudio==2.2.1) 
- (ImportError: cannot import name 'T_co' from 'torch.utils.data.dataset')
(reference: https://github.com/pytorch/pytorch/commit/f1df13f023d747af73bb51c2740959b699aeba66)

4. At this Point, if there's an error in the site_packages (check the traceback, it must be in your 'env' Folder) 
- pip uninstall tllib

5. Now, modify the code and remove the model_url part (changed because of pytorch Version) 
- do the patch below:
    - replace in the Import statements, 
    - model_url ---> ResNet18_Weights 
    - change wherever model_url was used to something like given below,
    **Original:**
    ![Image](https://github.com/user-attachments/assets/3785b407-a527-4a84-8a39-63f085a42e0e)
    **Modified:**
    ![Image](https://github.com/user-attachments/assets/df77c062-18bf-49f8-8f70-97faac64cd61)

6. Changed numpy Version to 1.23.5, 
- pip install numpy==1.23.5
	- REASONS:
	- a. tl Lib is old and thus, does NOT work with numpy 2.x (version < 2.0)
	- b. cfloat error (version < 1.24)(reference: https://stackoverflow.com/questions/74844262/how-can-i-solve-error-module-numpy-has-no-attribute-float-in-python)
	- c. numba==0.60.0 dependency (1.22 < version < 1.27) (reference: https://numba.readthedocs.io/en/stable/user/installing.html#version-support-information)

[requirements_new.txt](https://github.com/user-attachments/files/19089612/requirements_new.txt)

**Comment by shivanand-kundargi** [comment]
Thanks a lot @Ambuj-Choudha , your heads-up details for installation helped a lot, I was stuck for quite sometime now.

**Comment by Ambuj-Choudha** [comment]
@shivanand-kundargi would it make sense to open an issue for this and then reference my comment?, I realize that my comment might not be the easiest one to find, as it is commented under a "closed issue", nonetheless glad that the instructions helped!
